-- Riikide dimensioonitabeli loomine ja täitmine (41 unikaalset üksust)
CREATE OR REPLACE TABLE `optimal-cogency-483908-t3.kursusetoo_korghariduse_analyys.dim_country` AS
SELECT * FROM UNNEST([
  STRUCT('AT' AS country_code, 'Austria' AS country_name_et, 'Austria' AS country_name_en, 'Üksikriik' AS country_type_et, 'Single Country' AS country_type_en),
  ('BE', 'Belgia', 'Belgium', 'Üksikriik', 'Single Country'),
  ('BG', 'Bulgaaria', 'Bulgaria', 'Üksikriik', 'Single Country'),
  ('CH', 'Šveits', 'Switzerland', 'Üksikriik', 'Single Country'),
  ('CY', 'Küpros', 'Cyprus', 'Üksikriik', 'Single Country'),
  ('CZ', 'Tšehhi', 'Czechia', 'Üksikriik', 'Single Country'),
  ('DE', 'Saksamaa', 'Germany', 'Üksikriik', 'Single Country'),
  ('DK', 'Taani', 'Denmark', 'Üksikriik', 'Single Country'),
  ('EE', 'Eesti', 'Estonia', 'Üksikriik', 'Single Country'),
  ('EL', 'Kreeka', 'Greece', 'Üksikriik', 'Single Country'),
  ('ES', 'Hispaania', 'Spain', 'Üksikriik', 'Single Country'),
  ('FI', 'Soome', 'Finland', 'Üksikriik', 'Single Country'),
  ('FR', 'Prantsusmaa', 'France', 'Üksikriik', 'Single Country'),
  ('HR', 'Horvaatia', 'Croatia', 'Üksikriik', 'Single Country'),
  ('HU', 'Ungari', 'Hungary', 'Üksikriik', 'Single Country'),
  ('IE', 'Iirimaa', 'Ireland', 'Üksikriik', 'Single Country'),
  ('IS', 'Island', 'Iceland', 'Üksikriik', 'Single Country'),
  ('IT', 'Itaalia', 'Italy', 'Üksikriik', 'Single Country'),
  ('LT', 'Leedu', 'Lithuania', 'Üksikriik', 'Single Country'),
  ('LU', 'Luksemburg', 'Luxembourg', 'Üksikriik', 'Single Country'),
  ('LV', 'Läti', 'Latvia', 'Üksikriik', 'Single Country'),
  ('MT', 'Malta', 'Malta', 'Üksikriik', 'Single Country'),
  ('NL', 'Madalmaad', 'Netherlands', 'Üksikriik', 'Single Country'),
  ('NO', 'Norra', 'Norway', 'Üksikriik', 'Single Country'),
  ('PL', 'Poola', 'Poland', 'Üksikriik', 'Single Country'),
  ('PT', 'Portugal', 'Portugal', 'Üksikriik', 'Single Country'),
  ('RO', 'Rumeenia', 'Romania', 'Üksikriik', 'Single Country'),
  ('SE', 'Rootsi', 'Sweden', 'Üksikriik', 'Single Country'),
  ('SI', 'Sloveenia', 'Slovenia', 'Üksikriik', 'Single Country'),
  ('SK', 'Slovakkia', 'Slovakia', 'Üksikriik', 'Single Country'),
  ('UK', 'Ühendkuningriik', 'United Kingdom', 'Üksikriik', 'Single Country'),
  ('RS', 'Serbia', 'Serbia', 'Üksikriik', 'Single Country'),
  ('BA', 'Bosnia ja Hertsegoviina', 'Bosnia and Herzegovina', 'Üksikriik', 'Single Country'),
  ('TR', 'Türgi', 'Turkey', 'Üksikriik', 'Single Country'),
  ('AL', 'Albaania', 'Albania', 'Üksikriik', 'Single Country'),
  ('ME', 'Montenegro', 'Montenegro', 'Üksikriik', 'Single Country'),
  ('MK', 'Põhja-Makedoonia', 'North Macedonia', 'Üksikriik', 'Single Country'),
  ('GE', 'Gruusia', 'Georgia', 'Üksikriik', 'Single Country'),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'Üksikriik', 'Single Country'),
  ('EU28', 'Euroopa Liit (28 riiki)', 'European Union (28 countries)', 'Regioon', 'Region'),
  ('EU27_2020', 'Euroopa Liit (27 riiki alates 2020)', 'European Union (27 countries from 2020)', 'Regioon', 'Region')
]);
